<?php
$firephp = \FirePHP::getInstance(true);
$firephp->log('Ticket/view/ticket/ticket/add.phtml');
 
$title = 'Ticket hinzufügen';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form->setAttribute('action', $this->url('ticket', array('action' => 'add')));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('ticket'));
echo $this->formRow($form->get('kurz'));
echo $this->formRow($form->get('kontinentid'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();

