<?php
$firephp = \FirePHP::getInstance(true);
$firephp->log('Ticket/view/ticket/ticket/delete.phtml');
 
$title = 'Ticket löschen';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<p>
'<?php echo $this->escapeHtml($ticket->ticket); ?>' löschen?
</p>
<?php
$url = $this->url('ticket', array(
    'action' => 'delete',
    'id'     => $this->id,
));
?>
<form action="<?php echo $url; ?>" method="post">
<div>
<input type="hidden" name="id" value="<?php echo (int) $ticket->id; ?>" />
<input type="submit" name="del" value="Ja" />
<input type="submit" name="del" value="Nein" />
</div>
</form>

