<?php
$firephp = \FirePHP::getInstance(true);
$firephp->log('Ticket/view/ticket/ticket/edit.phtml');
 
$title = 'Ticket bearbeiten';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php
$form = $this->form;
$form->setAttribute('action', $this->url(
    'ticket',
    array(
        'action' => 'edit',
        'id'     => $this->id,
    )
));

$form->prepare();

// $firephp->log('Land/view/ticket/ticket/edit.phtml. kontinent=' . $form->get('kontinent'));

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('ticket'));
echo $this->formRow($form->get('kurz'));
echo $this->formRow($form->get('kontinentid'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();

