<?php
$firephp = \FirePHP::getInstance(true);
$firephp->log('Ticket/view/ticket/ticket/index.phtml');
 
$title = 'Tickets';
$this->headTitle($title);

$url_order = 'ASC';

if ($order_by == 'ticket')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'kurz')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
<a href="<?php echo $this->url('ticket', array('action'=>'add'));?>">Ticket hinzufügen</a>
</p>
<table class="table">
<tr>
<th>
<a href="<?php echo $this->url('ticket', array('order_by' => 'ticket', 'order' => $url_order)); ?>">Land <?php if ($order_by == 'ticket'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
</th>
<th>
<a href="<?php echo $this->url('ticket', array('order_by' => 'kurz', 'order' => $url_order)); ?>">Kurz <?php if ($order_by == 'kurz'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a></th>
<th>Kontinent</th>
<th>&nbsp;</th>
</tr>
<?php foreach ($tickets as $ticket) : ?>
<tr>
<td><?php echo $this->escapeHtml($ticket->ticket);?></td>
<td><?php echo $this->escapeHtml($ticket->kurz);?></td>
<td><?php echo $this->escapeHtml($ticket->kontinent);?></td>
<td>
<a href="<?php echo $this->url('ticket',
array('action'=>'edit', 'id' => $ticket->id));?>">Bearbeiten</a>
<a href="<?php echo $this->url('ticket',
array('action'=>'delete', 'id' => $ticket->id));?>">Löschen</a>
</td>
</tr>
<?php endforeach; ?>
</table>
