<?php
$firephp = \FirePHP::getInstance(true);
$firephp->log('Leben/view/leben/leben/index.phtml');

function date_mysql2german($datum)
{
    $d = explode("-", $datum);
    
    return sprintf("%02d.%02d.%04d", $d[2], $d[1], $d[0]);
}

$title = 'Leben';
$this->headTitle($title);
?>
<div>
<div class="rightside">
<div class="rightside_top">
<?php
echo $this->form()->openTag($this->selectform);
echo '<p class="selectform">' . $this->formRow($this->selectform->get('jahr')) . '</p>';
echo '<p class="selectform">' . $this->formRow($this->selectform->get('ortid')) . '</p>';
echo '<p class="selectform">' . $this->formRow($this->selectform->get('landid')) . '</p>';
echo '<p class="selectform">' . $this->formRow($this->selectform->get('suchtext')) . '</p>';
echo '<p class="selectform">' . $this->formRow($this->selectform->get('countperpage')) . '</p>';
echo $this->formSubmit($this->selectform->get('submit'));
echo $this->form()->closeTag();
?>
</div>
<div class="rightside_bottom">
<p>
<a href="<?php echo $this->url('leben', array('action'=>'add'));?>">Leben hinzufügen</a>
</p>
<p>
Anzahl: <?php echo $this->paginator->getTotalItemCount(); ?>
</p>
<h3><?php echo $this->escapeHtml($title); ?></h3>
</div>
</div>
<div class="leftside">
<table class="table">
<tr>
<th>Datum</th>
<th>Ort</th>
<th>Land</th>
<th>Beschreibung</th>
<th></th>
</tr>
<?php foreach ($this->paginator as $leben) : ?>
<tr class="firstline" id="<?php echo $this->escapeHtml($leben->id);?>">
<td class="datum">
<?php
echo $this->escapeHtml(date_mysql2german($leben->datumvon));

if ($leben->datumvon != $leben->datumbis)
{
    echo ' - ' . $this->escapeHtml(date_mysql2german($leben->datumbis));
}
?>
</td>
<td><?php echo $this->escapeHtml($leben->ort);?></td>
<td><?php echo $this->escapeHtml($leben->land);?></td>
<td><?php echo $this->escapeHtml($leben->beschreibung);?></td>
<td class="editing"
><a href="<?php echo $this->url('leben', array(
            'action' => 'edit',
            'id' => $leben->id
    ));?>">Edit</a>
<a href="<?php echo $this->url('leben', array(
            'action' => 'delete',
            'id' => $leben->id
    ));?>">Del</a>
<a href="javascript:leben_move(<?php echo $leben->id;?>, +1)">Up</a>
<a href="javascript:leben_move(<?php echo $leben->id;?>, -1)">Down</a>    
</td>
</tr>
<?php
if ($leben->bemerkung != '')
{
    echo '<tr class="secondline" id="' . $this->escapeHtml($leben->id) . '">';
    echo '<td colspan="3" style="border-top: 0px; padding-top: 0px;"></td>';
    echo '<td colspan="4" style="border-top: 0px; padding-top: 0px;">' . $this->escapeHtml($leben->bemerkung) . '</td>';
    echo '</tr>';
}
?>

<?php endforeach; ?>
</table>
<hr>
<?php
if ($this->paginator->count() > 1)
{
    echo $this->paginationControl($this->paginator, 'sliding', array(
            'partial/paginator.phtml',
            'Serie'
    ), array(
            'route' => 'leben',
	    )
	);
}
?>
</div>
	<div style="clear: both"></div>
</div>
<?php
$this->inlineScript()->prependFile($this->basePath() . '/js/ofa_leben.js');
?>
