<?php
use Zend\Session\Container;

$title = 'Alben';
$owners = array("Alle", "JR", "EP");

$this->headTitle($title);
?>
<div>
<div class="rightside">
<div id="rightside_top" class="rightside_top">
<?php
echo $this->form()->openTag($this->selectform);
echo '<p class="selectform">' . $this->formRow($this->selectform->get('ownerid')) . '</p>';
echo '<p class="selectform">' . $this->formRow($this->selectform->get('roomid')) . '</p>';
echo '<hr class="selectform">';
echo '<p class="selectform">' . $this->formRow($this->selectform->get('albumartist')) . '</p>';
echo '<p class="selectform">' . $this->formRow($this->selectform->get('suchtext')) . '</p>';
echo '<p class="selectform">' . $this->formRow($this->selectform->get('rating')) . $this->formRow($this->selectform->get('countperpage')) . '</p>';
echo '<p class="selectform">' . $this->formSubmit($this->selectform->get('submit')) . '</p>';
echo '<hr class="selectform">';
echo $this->form()->closeTag();
?>
</div>
<div class="rightside_information">
<span id="albuminformation"></span>
</div>
<div class="rightside_bottom">
<hr class="selectform">
<p><span id="album_info"></span></p>
<p>
	<a href="javascript:album_controlTrack('info');"><span class="ui-icon ui-icon-info"></span></a> |
	<a href="javascript:album_controlTrack('previous');"><span class="ui-icon ui-icon-seek-prev"></span></a> |
	<a href="javascript:album_controlTrack('stop');"><span class="ui-icon ui-icon-stop"></span></a> |
	<a href="javascript:album_controlTrack('pause');"><span class="ui-icon ui-icon-pause"></span></a> |
	<a href="javascript:album_controlTrack('next');"><span class="ui-icon ui-icon-seek-next"></span></a>
</p>
<hr class="selectform">
<p>
Anzahl: <?php echo $this->paginator->getTotalItemCount(); ?>
</p>
<h3><?php echo $this->escapeHtml($title); ?></h3></div>
</div>
<div class="leftside">
<div id="leftside_album_tabelle" class="leftside_album_tabelle">
<table class="table">
<tr>
<th><a href="<?php echo $this->url('album'); ?>">Artist</a></th>
<th><a href="<?php echo $this->url('album', array('order_by' => 'album')); ?>">Album</a></th>
<th><a href="<?php echo $this->url('album', array('order_by' => 'jahr')); ?>">Jahr</a></th>
<th>Genre</th>
<th>Anzahl</th>
<th>Owner</th>
<th>Rating</th>
<th>S/L</th>
<th>&nbsp;</th>
</tr>
<?php foreach ($this->paginator as $album) : ?>
<tr class="firstline" id="<?php echo $this->escapeHtml($album->musicbrainz_albumid);?>">
<td><?php echo $this->escapeHtml($album->albumartist);?></td>
<td><?php echo $this->escapeHtml($album->album);?></td>
<td>
<?php
$jahr = '';
if ($album->originalyear > 0) {
	$jahr = '' . $album->originalyear . ' ';
}
if ($album->year > 0 && $album->originalyear != $album->year) {
	$jahr .= '(' . $album->year . ')';
}
echo $this->escapeHtml($jahr);
?>
</td>
<td><?php echo $this->escapeHtml($album->genre);?></td>
<td class="shortnumber"><?php echo $this->escapeHtml($album->anzahl);?></td>
<td><span id="owner_<?php echo $album->musicbrainz_albumid;?>">
<?php
for ($i = 0; $i < count($owners); $i++) {
	if ($album->ownerid == $i) {
		echo '<b>' . $owners[$i] . '</b>';
	} else {
		echo '<a href="javascript:album_setOwner(\'' .  $album->musicbrainz_albumid . '\', '  . $i . ');">' . $owners[$i] . '</a>';
	}

	if ($i < count($owners) - 1) {
		echo ' | ';
	}
}
?>
</span></td>
<td><span id="rating_<?php echo $album->musicbrainz_albumid;?>">
<?php
for ($i = 0; $i <= 5; $i++) {
	if ($album->rating == $i) {
		echo '<b>' . $i . '</b>';
	} else {
		echo '<a href="javascript:album_setRating(\'' .  $album->musicbrainz_albumid . '\', '  . $i . ');">' . $i . '</a>';
	}

	if ($i < 5) {
		echo ' | ';
	}
}
?>
</span></td>
<td><span id="studio_<?php echo $album->musicbrainz_albumid;?>">
<?php
if ($album->studio == 1) {
	echo '<a href="javascript:album_setStudioLive(\'' .  $album->musicbrainz_albumid . '\', 0);">Studio</a>';
} else {
	echo '<a href="javascript:album_setStudioLive(\'' .  $album->musicbrainz_albumid . '\', 1);">Live</a>';
}
?>
</span></td>
<td>
<a href="javascript:album_picAdded('<?php echo $album->musicbrainz_albumid;?>');">Pic</a>
<a href="<?php echo $this->url('album',	array('action'=>'delete', 'id' => $album->musicbrainz_albumid));?>">Del</a>
<a href="javascript:album_playAlbum('<?php echo $album->musicbrainz_albumid;?>');">Play</a>
</td>
</tr>
<?php endforeach; ?>
</table>
<hr>
<?php
if ($this->paginator->count() > 1)
{
	echo $this->paginationControl(
	    $this->paginator,
	    'sliding',
	    array('partial/paginator.phtml', 'Album'),
	    array(
	        'route' => 'album',
	    )
	);
}
?>
</div>

</div>
<div style="clear:both"></div>
</div>
<?php
$this->headLink()->appendStylesheet($this->basePath() . '/css/jquery-ui.css');
$this->headLink()->appendStylesheet($this->basePath() . '/css/jquery-ui.theme.min.css');
$this->headLink()->appendStylesheet($this->basePath() . '/js/fancybox/jquery.fancybox.css');
$this->headLink()->appendStylesheet($this->basePath() . '/css/jquery.jscrollpane.css');
$this->headScript()->appendFile($this->basePath() . '/js/jquery-ui.min.js');
$this->headScript()->appendFile($this->basePath() . '/js/jquery.mousewheel.js');
$this->headScript()->appendFile($this->basePath() . '/js/jquery.jscrollpane.min.js');
$this->headScript()->appendFile($this->basePath() . '/js/fancybox/jquery.fancybox.js');
$this->headScript()->appendFile($this->basePath() . '/js/js.cookie.js');
$this->inlineScript()->prependFile($this->basePath() . '/js/ofa_album.js');
?>
