<?php
use Zend\Session\Container;

$title = 'Tracks';
$this->headTitle($title);
?>
<div>
<div class="rightside">
<div class="rightside_top">
<?php
echo $this->form()->openTag($this->selectform);
echo '<p class="selectform">' . $this->formRow($this->selectform->get('albumartist')) . '</p>';
echo '<p class="selectform">' . $this->formRow($this->selectform->get('album')) . '</p>';
echo '<p class="selectform">' . $this->formRow($this->selectform->get('genre')) . '</p>';
echo '<p class="selectform">' . $this->formRow($this->selectform->get('suchtext')) . '</p>';
echo '<p class="selectform">' . $this->formRow($this->selectform->get('countperpage')) . '</p>';
echo '<p class="selectform">' . $this->formSubmit($this->selectform->get('submit')) . '</p>';
echo '<hr class="selectform">';
echo $this->form()->closeTag();
?>
</div>
<div class="rightside_information">
<span id="trackinformation"></span>
</div>
<div class="rightside_bottom">
<hr class="selectform">
<p>
Anzahl: <?php echo $this->paginator->getTotalItemCount(); ?>
</p>
<h3><?php echo $this->escapeHtml($title); ?></h3></div>
</div>
<div class="leftside">
<table class="table">
<tr>
<th><a href="<?php echo $this->url('track', array('order_by' => 'title')); ?>">Titel</a></th>
<th><a href="<?php echo $this->url('track', array('order_by' => 'artist')); ?>">Artist</a></th>
<th>Album</th>
<th>Nr</th>
<th>Dauer</th>
<th>Genre</th>
<th>&nbsp;</th>
</tr>
<?php foreach ($this->paginator as $track) : ?>
<tr class="firstline" id="<?php echo $this->escapeHtml($track->musicbrainz_trackid);?>">
<td><?php echo $this->escapeHtml($track->title);?></td>
<td>
<?php
$artist = $track->artist;
if ($artist == '') {
	$artist = $track->albumartist;
}
if ($artist == 'AC') {
	$artist = $track->albumartist;
}
echo $this->escapeHtml($artist);
?>
</td>
<td>
<?php
$album = $track->album;
if ($track->totaldiscs > 1) {
	$album .= ' (' . $track->discnumber . ')';
}
echo $this->escapeHtml($album);
?>
</td>
<td class="shortnumber"><?php echo $this->escapeHtml($track->track);?></td>
<td><?php echo $this->escapeHtml($track->duration);?></td>
<td><?php echo $this->escapeHtml($track->genre);?></td>
<td>
<a href="javascript:track_playTrack('<?php echo $track->musicbrainz_trackid;?>');">Play</a>
<a href="javascript:track_addToRunningTracks('<?php echo $track->musicbrainz_trackid;?>');">Add</a>
</td>
</tr>
<?php endforeach; ?>
</table>
<hr>
<?php
if ($this->paginator->count() > 1)
{
	echo $this->paginationControl(
	    $this->paginator,
	    'sliding',
	    array('partial/paginator.phtml', 'Track'),
	    array(
	        'route' => 'track',
	    )
	);
}
?>
</div>
<div style="clear:both"></div>
</div>
<?php
$this->headLink()->appendStylesheet($this->basePath() . '/css/jquery-ui.css');
$this->headLink()->appendStylesheet($this->basePath() . '/js/fancybox/jquery.fancybox.css');
$this->headScript()->appendFile($this->basePath() . '/js/jquery-ui.min.js');
$this->headScript()->appendFile($this->basePath() . '/js/fancybox/jquery.fancybox.js');
$this->inlineScript()->prependFile($this->basePath() . '/js/ofa_track.js');
?>
