<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php
        echo $this->headTitle($this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false);

        echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge');

        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
            ->prependStylesheet($this->basePath() . '/css/ofa.css')
            ->prependStylesheet($this->basePath() . '/css/jquery-ui.theme.min.css')
            ->prependStylesheet($this->basePath() . '/css/jquery-ui.css')
            ->prependStylesheet($this->basePath() . '/css/style.css')
            ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
            ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css');

        echo $this->headScript()
            ->prependFile($this->basePath() . '/js/ofa.js')
            ->prependFile($this->basePath() . '/js/bootstrap.bundle.min.js')
            ->prependFile($this->basePath() . '/js/jquery-ui.min.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',));
        ?>
    </head>
    <body>
    <nav class="navbar navbar-expand-lg bg-light fixed-top">
        <div class="container-fluid">
            <a class="navbar-brand" href="/">OneForAll</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarText">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
<?php
echo '<li class="nav-item"><a class="nav-link active" aria-current="page" href="' . $this->url('home') . '">' . $this->translate('Home') . '</a></li>';
echo '<li class="nav-item"><a class="nav-link" href="' . $this->url('leben') . '">' . $this->translate('Leben') . '</a></li>';
echo '<li class="nav-item"><a class="nav-link" href="' . $this->url('bild') . '">' . $this->translate('Bilder') . '</a></li>';
echo '<li class="nav-item"><a class="nav-link" href="' . $this->url('serie') . '">' . $this->translate('Serien') . '</a></li>';
echo '<li class="nav-item"><a class="nav-link" href="' . $this->url('web') . '">' . $this->translate('Web') . '</a></li>';
echo '<li class="nav-item"><a class="nav-link" href="' . $this->url('land') . '">' . $this->translate('Länder') . '</a></li>';
echo '<li class="nav-item"><a class="nav-link" href="' . $this->url('ort') . '">' . $this->translate('Orte') . '</a></li>';
echo '<li class="nav-item"><a class="nav-link" href="' . $this->url('motiv') . '">' . $this->translate('Motive') . '</a></li>';
echo '<li class="nav-item"><a class="nav-link" href="' . $this->url('label') . '">' . $this->translate('Labels') . '</a></li>';
echo '<li class="nav-item"><a class="nav-link" href="' . $this->url('album') . '">' . $this->translate('Alben') . '</a></li>';
echo '<li class="nav-item"><a class="nav-link" href="' . $this->url('track') . '">' . $this->translate('Tracks') . '</a></li>';
echo '<li class="nav-item"><a class="nav-link" href="' . $this->url('playlist') . '">' . $this->translate('Playlists') . '</a></li>';
?>

                <!-- <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="#">Home</a>
                </li>
                <li class="nav-item">
                <a class="nav-link" href="#">Features</a>
                </li>
                <li class="nav-item">
                <a class="nav-link" href="#">Pricing</a>
                </li> -->
            </ul>
            <span class="navbar-text">
                Willkommen!
            </span>
            </div>
        </div>
    </nav>

        <div class="container">
	        <?php echo $this->content; ?>
            <footer>

            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
